### ISSUE TITLE
Flink starrocks stream JOB found restarting due to Connection fe timed 呕吐

### ISSUE THREAD

**Issue by zbingwen** [StarRocks/starrocks-kubernetes-operator#321]
## Please complete the following information

- Operator Version: [e.g. v1.8.6]
- Chart Name: [e.g. kube-starrocks]
- Chart Version [e.g. v1.8.6]

**Comment by zbingwen** [comment]
I found below information from fe-leader:
```
-cluster-be-search.staging-ydata-v30.svc.cluster.local
2023-11-22 11:06:18,045 WARN (thrift-server-pool-5|180) [SystemInfoService.getBackendWithBePort():556] failed to get right ip by fqdn starrocks-cluster-be-0.starrocks-cluster-be-search.staging-ydata-v30.svc.cluster.local
2023-11-22 11:06:18,467 WARN (thrift-server-pool-4|179) [SystemInfoService.getBackendWithBePort():556] failed to get right ip by fqdn starrocks-cluster-be-0.starrocks-cluster-be-search.staging-ydata-v30.svc.cluster.local
2023-11-22 11:06:18,589 WARN (thrift-server-pool-151|485) [SystemInfoService.getBackendWithBePort():556] failed to get right ip by fqdn starrocks-cluster-be-0.starrocks-cluster-be-search.staging-ydata-v30.svc.cluster.local
2023-11-22 11:06:19,466 WARN (thrift-server-pool-6|181) [SystemInfoService.getBackendWithBePort():556] failed to get right ip by fqdn starrocks-cluster-be-0.starrocks-cluster-be-search.staging-ydata-v30.svc.cluster.local
2023-11-22 11:06:19,467 WARN (thrift-server-pool-5|180) [SystemInfoService.getBackendWithBePort():556] failed to get right ip by fqdn starrocks-cluster-be-0.starrocks-cluster-be-search.staging-ydata-v30.svc.cluster.local
2023-11-22 11:06:19,589 WARN (thrift-server-pool-152|486) [SystemInfoService.getBackendWithBePort():556] failed to get right ip by fqdn starrocks-cluster-be-0.starrocks-cluster-be-search.staging-ydata-v30.svc.cluster.local
2023-11-22 11:06:20,468 WARN (thrift-server-pool-4|179) [SystemInfoService.getBackendWithBePort():556] failed to get right ip by fqdn starrocks-cluster-be-0.starrocks-cluster-be-search.staging-ydata-v30.svc.cluster.local
2023-11-22 11:06:20,590 WARN (thrift-server-pool-150|484) [SystemInfoService.getBackendWithBePort():556] failed to get right ip by fqdn starrocks-cluster-be-0.starrocks-cluster-be-search.staging-ydata-v30.svc.cluster.local
2023-11-22 11:06:21,468 WARN (thrift-server-pool-6|181) [SystemInfoService.getBackendWithBePort():556] failed to get right ip by fqdn starrocks-cluster-be-0.starrocks-cluster-be-search.staging-ydata-v30.svc.cluster.local
2023-11-22 11:06:21,590 WARN (thrift-server-pool-151|485) [SystemInfoService.getBackendWithBePort():556] failed to get right ip by fqdn starrocks-cluster-be-0.starrocks-cluster-be-search.staging-ydata-v30.svc.cluster.local
2023-11-22 11:06:22,019 WARN (thrift-server-pool-152|486) [SystemInfoService.getBackendWithBePort():556] failed to get right ip by fqdn starrocks-cluster-be-0.starrocks-cluster-be-search.staging-ydata-v30.svc.cluster.local
2023-11-22 11:06:22,020 WARN (thrift-server-pool-150|484) [SystemInfoService.getBackendWithBePort():556] failed to get right ip by fqdn starrocks-cluster-be-0.starrocks-cluster-be-search.staging-ydata-v30.svc.cluster.local
2023-11-22 11:06:22,469 WARN (thrift-server-pool-5|180) [SystemInfoService.getBackendWithBePort():556] failed to get right ip by fqdn starrocks-cluster-be-0.starrocks-cluster-be-search.staging-ydata-v30.svc.cluster.local
2023-11-22 11:06:22,591 WARN (thrift-server-pool-151|485) [SystemInfoService.getBackendWithBePort():556] failed to get right ip by fqdn starrocks-cluster-be-0.starrocks-cluster-be-search.staging-ydata-v30.svc.cluster.local
2023-11-22 11:06:23,003 WARN (heartbeat-mgr-pool-1|129) [HeartbeatMgr$BackendHeartbeatHandler.call():315] backend heartbeat got exception, addr: starrocks-cluster-be-0.starrocks-cluster-be-search.staging-ydata-v30.svc.cluster.local:9050
org.apache.thrift.transport.TTransportException: java.net.UnknownHostException: starrocks-cluster-be-0.starrocks-cluster-be-search.staging-ydata-v30.svc.cluster.local
        at org.apache.thrift.transport.TSocket.open(TSocket.java:226) ~[libthrift-0.13.0.jar:0.13.0]
        at com.starrocks.common.GenericPool$ThriftClientFactory.create(GenericPool.java:144) ~[starrocks-fe.jar:?]
        at com.starrocks.common.GenericPool$ThriftClientFactory.create(GenericPool.java:129) ~[starrocks-fe.jar:?]
        at org.apache.commons.pool2.BaseKeyedPooledObjectFactory.makeObject(BaseKeyedPooledObjectFactory.java:62) ~[commons-pool2-2.3.jar:2.3]
        at org.apache.commons.pool2.impl.GenericKeyedObjectPool.create(GenericKeyedObjectPool.java:1036) ~[commons-pool2-2.3.jar:2.3]
        at org.apache.commons.pool2.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:356) ~[commons-pool2-2.3.jar:2.3]
        at org.apache.commons.pool2.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:278) ~[commons-pool2-2.3.jar:2.3]
        at com.starrocks.common.GenericPool.borrowObject(GenericPool.java:101) ~[starrocks-fe.jar:?]
        at com.starrocks.system.HeartbeatMgr$BackendHeartbeatHandler.call(HeartbeatMgr.java:265) ~[starrocks-fe.jar:?]
        at com.starrocks.system.HeartbeatMgr$BackendHeartbeatHandler.call(HeartbeatMgr.java:251) ~[starrocks-fe.jar:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        at java.lang.Thread.run(Thread.java:829) ~[?:?]
Caused by: java.net.UnknownHostException: starrocks-cluster-be-0.starrocks-cluster-be-search.staging-ydata-v30.svc.cluster.local
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:229) ~[?:?]
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:?]
        at java.net.Socket.connect(Socket.java:609) ~[?:?]
        at org.apache.thrift.transport.TSocket.open(TSocket.java:221) ~[libthrift-0.13.0.jar:0.13.0]
        ... 13 more
2023-11-22 11:06:23,004 WARN (heartbeat mgr|13) [HeartbeatMgr.runAfterCatalogReady():164] get bad heartbeat response: type: BACKEND, status: BAD, msg: java.net.UnknownHostException: starrocks-cluster-be-0.starrocks-cluster-be-search.staging-ydata-v30.svc.cluster.local
2023-11-22 11:06:23,469 WARN (thrift-server-pool-4|179) [SystemInfoService.getBackendWithBePort():556] failed to get right ip by fqdn starrocks-cluster-be-0.starrocks-cluster-be-search.staging-ydata-v30.svc.cluster.local
2023-11-22 11:06:23,591 WARN (thrift-server-pool-152|486) [SystemInfoService.getBackendWithBePort():556] failed to get right ip by fqdn starrocks-cluster-be-0.starrocks-cluster-be-search.staging-ydata-v30.svc.cluster.local
```

**Comment by zbingwen** [comment]
@kevincai Please help me , thank you in advance.

**Comment by yandongxiao** [comment]
Please see https://github.com/StarRocks/starrocks-kubernetes-operator/blob/main/doc/load_data_using_stream_load_howto.md

**Comment by zbingwen** [comment]
都部署在同一个K8S集群，不存在内外网问题。 FLINK JOB 大部分都正常，是时不时出现该异常情况。

**Comment by yandongxiao** [comment]
This is a DNS Resolution issue, can you please give the network & DNS configuration in k8s?

**Comment by yandongxiao** [comment]
If you are using coreDNS, https://github.com/coredns/coredns/issues/4297 and https://github.com/coredns/coredns/issues/4357 issues may help you. 

1.  one user said: I have upgraded our cluster to coredns:v1.7.0 and increased cpu resource 0.1 -> 0.5 cpu. Last 10 days we had 0 dns issue. I installed some tools to find sender. For now I will close this issue.
2. deploying node local dns cache to see if it helps.

Hope these message may help you. And If you have solved the problem, please write a resolution.

**Comment by zbingwen** [comment]
@yandongxiao    coredns: 1.9.3.10  k8s: v1.22.15-aliyun.1   we use aliyun. 

I add local /etc/hosts file ，but report this same error.

**Comment by zbingwen** [comment]
我将fe 三个节点高可用模式，缩容为一个fe节点，该问题就消失了。

**Comment by yandongxiao** [comment]
Two conclusions can be drawn from the FE Leader's logs:
1. Multiple threads are reporting SystemInfoService.getBackendWithBePort():556 at the same time. It is suspected that the JVM DNS Cache has expired, but it also failed when trying to get the domain name from the DNS Server.

2. The context of org.apache.thrift.transport.TTransportException is that when the FE sends HeartBeat information to the BE, the domain name set by the Thrift Client directly calls the DNS Server to get the domain name, but it fails.

Whether /etc/hosts takes effect or not? And scale down FE replicas to 1 may not the root cause.

**Comment by yandongxiao** [comment]
Has the BE's Pod ever experienced a restart ?

**Comment by zbingwen** [comment]
BE‘s pod  is not restart .  starrocks cluster health is ok by below command. 

SHOW PROC '/frontends'; 
SHOW PROC '/backends';

**Comment by zbingwen** [comment]
@yandongxiao starrocks stream loading need session keep？

**Comment by zbingwen** [comment]
@yandongxiao  Yes , we can reduce the frequency of Stream Load and increase the amount of data for each Stream Load. 
but still report this.

**Comment by alanssec** [comment]
Hello,

Our team is using the starrocks-spark-connector-3.4_2.12:1.1.2, and we are experiencing a similar FE connection timeout issue. While we understand that your case involves the Flink connector, we wanted to ask if you are also using TKGM, as we are, to determine if that might be a contributing factor to the problem.

For reference, here's the related GitHub issue we encountered: [StarRocks Issue #50948](https://github.com/StarRocks/starrocks/issues/50948).

**Comment by mmniazi-mwam** [comment]
Hi I am facing this issue as well. Any idea how I can debug/fix this?
